spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: vikram
    password: vikram
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
