#spring.application.name=ecom-application
#server.port=8082
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888

