#spring.application.name=ecom-application
#server.port=8082
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5432/orderDB
    username: vikram
    password: vikram
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083

